spring.application.name=devkudos

# Diz para o Spring mostrar no terminal os comandos SQL que ele está gerando
spring.jpa.show-sql=true

# Permite que a gente acesse o banco de dados pelo navegador para ver as tabelas!
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Diz pro Spring recriar as tabelas toda vez que a gente rodar o app (ótimo para testes)
spring.jpa.hibernate.ddl-auto=update